name: DI-CL PIPELINE

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build_and_push:
    runs-on: runner-1

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build backend image
        run: |
          docker build -t mdzihad22/voting-backend:${{env.IMAGE_TAG}} ./backend

      - name: Push backend image
        run: |
          docker push mdzihad22/voting-backend:${{env.IMAGE_TAG}}

      - name: Build frontend image
        run: |
          docker build \
            --build-arg VITE_API_URL=${{ secrets.FRONTEND_API_URL }} \
            --build-arg VITE_SOCKET_URL=${{ secrets.FRONTEND_SOCKET_URL }} \
            -t mdzihad22/ngi-front:${{env.IMAGE_TAG}} \
            ./frontend

      - name: Push frontend image
        run: |
          docker push mdzihad22/ngi-front:${{env.IMAGE_TAG}}

  deploy_to_ec2:
    runs-on: runner-1
    needs: build_and_push

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_SERVER_HOST }}
          username: ${{ secrets.EC2_SERVER_USER }}
          key: ${{ secrets.EC2_SERVER_SSH_KEY }}
          script: |
            cd /home/ubuntu

            # If repo does not exist, clone it
            if [ ! -d "docker-voting-app" ]; then
              git clone https://github.com/ZIHAD22/docker-voting-app.git
            else
              cd docker-voting-app
              git pull origin main
              cd ..
            fi

            cd docker-voting-app

            echo "Using latest docker-compose.yml..."

            if [ ! -f ".env" ]; then
              echo "Creating .env file"
              touch .env
            fi

            if ! grep -q "^IMAGE_TAG=" .env; then
              echo "IMAGE_TAG=placeholder" >> .env
            fi

            sed -i "s/^IMAGE_TAG=.*/IMAGE_TAG=${{ env.IMAGE_TAG }}/" .env

            echo "Updated IMAGE_TAG to ${{ env.IMAGE_TAG }}"

            #Deploy using updated compose file
            docker compose pull
            docker compose up -d
            docker exec -it backend sh
            node seed.js

            echo "Deployment complete!"
